<a href="https://colab.research.google.com/github/AJAYM888/Course_PyTorch/blob/main/00_Exercises_PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals Exercises

### 1. Documentation reading
A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):

* The documentation on torch.Tensor: https://pytorch.org/docs/stable/tensors.html#torch-tensor.
* The documentation on torch.cuda: https://pytorch.org/docs/main/notes/cuda.html#cuda-semantics



In [ ]:
# No code

### 2. Create a random tensor with shape (7, 7).


In [2]:
import torch

# Create random tensor
random_tensor = torch.rand(7,7)
random_tensor

tensor([[0.9281, 0.4365, 0.9115, 0.6516, 0.9136, 0.2384, 0.5167],
        [0.5790, 0.3349, 0.1391, 0.0595, 0.0935, 0.5191, 0.3101],
        [0.6928, 0.3837, 0.4593, 0.4205, 0.4316, 0.2027, 0.2687],
        [0.3226, 0.9320, 0.6599, 0.2013, 0.1879, 0.8473, 0.7507],
        [0.6328, 0.7287, 0.5942, 0.0609, 0.3064, 0.3178, 0.4249],
        [0.5534, 0.7035, 0.2794, 0.7124, 0.4496, 0.5751, 0.2084],
        [0.4004, 0.1272, 0.8790, 0.0389, 0.8341, 0.6430, 0.8035]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).


In [14]:
# create random tensor B

random_tensor_B = torch.rand(1,7)
print(f"Before transpose: {random_tensor_B}")
print(f"Tensor B: {random_tensor_B.T}")
print(f"Tensor B: {random_tensor_B.T.shape}")

perform_matrix_multiplication = torch.matmul(random_tensor, random_tensor_B.T)
perform_matrix_multiplication


Before transpose: tensor([[0.2638, 0.2390, 0.0462, 0.2451, 0.6384, 0.9270, 0.5376]])
Tensor B: tensor([[0.2638],
        [0.2390],
        [0.0462],
        [0.2451],
        [0.6384],
        [0.9270],
        [0.5376]])
Tensor B: torch.Size([7, 1])


tensor([[1.0715],
        [1.0039],
        [1.2917],
        [1.5750],
        [2.1247],
        [1.4672],
        [1.3049]])

### 4. Set the random seed to 0 and do 2 & 3 over again.


In [32]:
# Set manual seed
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)
# Create two random tensors

random_tensor = torch.rand(7,7)

random_tensor_B = torch.rand(1,7)

# Matrix multiply tensors
perform_matrix_multiplication = torch.matmul(random_tensor, random_tensor_B.T)
perform_matrix_multiplication, perform_matrix_multiplication.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

In [6]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

### 5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one)

In [7]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)