<a href="https://colab.research.google.com/github/AJAYM888/Course_PyTorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals

In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1+cu121


In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


## Intro to tensors

### creating tensors

PyTorch tensor are created using 'torch.Tensor()' = add link

In [ ]:
# scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# get tensor back as python int

scalar.item()

7

In [ ]:
# vector - has magnitude (how far) and direction (which way)
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#TENSOR

TENSOR = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [ ]:
#TENSOR

TENSOR = torch.tensor([[[[[1,2,3],[3,6,9],[2,4,5]]]]])
TENSOR

tensor([[[[[1, 2, 3],
           [3, 6, 9],
           [2, 4, 5]]]]])

In [ ]:
#TENSOR

TENSOR = torch.tensor([[[[[1,2,3],[3,6,9],[2,4,5]]]]])
TENSOR

tensor([[[[[1, 2, 3],
           [3, 6, 9],
           [2, 4, 5]]]]])

In [ ]:
TENSOR.ndim

5

In [ ]:
TENSOR.shape

torch.Size([1, 1, 1, 3, 3])

In [ ]:
#TENSOR

TENSOR = torch.tensor([[[[[1,2,3],[3,6,9],[2,4,5],[5,6,7]]]]])
TENSOR

tensor([[[[[1, 2, 3],
           [3, 6, 9],
           [2, 4, 5],
           [5, 6, 7]]]]])

In [ ]:
TENSOR.ndim

5

In [ ]:
TENSOR.shape

torch.Size([1, 1, 1, 4, 3])

In [ ]:
#TENSOR

TENSOR = torch.tensor([[[[[1,2,3],[3,6,9],[2,4,5],[5,6,7], [7,8,9]]]]])
TENSOR

tensor([[[[[1, 2, 3],
           [3, 6, 9],
           [2, 4, 5],
           [5, 6, 7],
           [7, 8, 9]]]]])

In [ ]:
TENSOR.ndim


5

In [ ]:
TENSOR.shape

torch.Size([1, 1, 1, 5, 3])

In [ ]:
#TENSOR

TENSOR = torch.tensor([[[[[1,2,3],[3,6,9],[2,4,5],[5,6,7], [7,8,9], [9,10,11]]]]])
TENSOR

tensor([[[[[ 1,  2,  3],
           [ 3,  6,  9],
           [ 2,  4,  5],
           [ 5,  6,  7],
           [ 7,  8,  9],
           [ 9, 10, 11]]]]])

## Random Tensors

Why random tensors?

Rand tensors are important because the way many neural networks learn is that they start with tensor full of random numbers and then adjust those random numbers to better represent the data.


'start with rand numbers -> look at data -> update rand numbers -> look at data -> update random numbers'

In [ ]:
### create a random tensors of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor


tensor([[0.1000, 0.3180, 0.3293, 0.2707],
        [0.1834, 0.3980, 0.9114, 0.7280],
        [0.2271, 0.8037, 0.9872, 0.0295]])

In [ ]:
random_tensor.ndim

2

In [ ]:
# create a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(224, 224, 3)) #height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeros & Ones

In [ ]:
## create tensors with zeros & ones

zeros = torch.zeros(size=(3,4))
zeros
#zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(size=(4,4))
ones
#ones*random_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

## Tensor Range: Creating tensors with range & tensors-like

In [ ]:
# use torch.range
torch.arange(0,30)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
# use torch.range gets deprecated, use like below : arange()
two_twenty = torch.arange(start=2 , end=2000, step=200)
two_twenty

tensor([   2,  202,  402,  602,  802, 1002, 1202, 1402, 1602, 1802])

In [ ]:
# creating tensor like

ten_zeros = torch.zeros_like(input=two_twenty)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor DataTypes

**Note: ** Tensor datatypes is one of the three big issues in pytorch & DeepLearning
1. Tensors not right datatype
2. Tensor not in correct shape
3. Tensors not on the right device

In [5]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None, device=None, requires_grad=False) # what datatype is the tensor (e.g. float32 or float16)
float_32_tensor

tensor([3., 6., 9.])

In [6]:
# @title
float_16_tensor = float_32_tensor.type(torch.float16)

#float_16_tensor = float_32_tensor.type(torch.half)

float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [7]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [8]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [9]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

## Getting Information from tensors (tensor attributes)

1. Tensors not right datatype - to get datatype from a tensor, use tensor.dtype
2. Tensor not in correct shape - to get shape from a tensor, use tensor.shape
3. Tensors not on the right device - to get device from a tensor, use tensor.device


In [8]:
# create a tensor

some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.7286, 0.8056, 0.8441, 0.6022],
        [0.5897, 0.6842, 0.6022, 0.8134],
        [0.3148, 0.0895, 0.8091, 0.2022]])

In [5]:
# Find out details about tensor

print(some_tensor)
print(f"DataType of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.0044, 0.0455, 0.0402, 0.8669],
        [0.3279, 0.3908, 0.6597, 0.8868],
        [0.3097, 0.0760, 0.5676, 0.0240]])
DataType of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


## Manipulating Tensors (Tensor operations)

Tensor operations include:

* Addtion
* Substraction
* Multiplication (element-wise)
* Divison
* Matrix Multiplication

In [4]:
# create a tensor

tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [5]:
# Multiply tensor

tensor = torch.tensor([1,2,3])

tensor * 10

tensor([10, 20, 30])

In [6]:
# substration

tensor - 20

tensor([-19, -18, -17])

In [7]:
# Try out pytorch in-built functions

torch.mul(tensor, 20)
#torch.add(tensor, 20)
#torch.sub(tensor, 20)

tensor([20, 40, 60])

### Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

Docs: https://www.mathsisfun.com/algebra/matrix-multiplying.html
Calculator: http://matrixmultiplication.xyz/

There are two main rules that performing matrix multiplication needs to satisfy:

1. The **inner dimensions** must match:
* `(3,2) @ (3,2) ` won't work
* `(2,3) @ (3,2) ` will work
* `(3,2) @ (2,3) ` will work

2. The resulting matrix has the shape of the **outer dimensions**:

* `(3,2) @ (2,3)` -> `(2,2)`
* `(3,2) @ (2,3)` -> `(3,3)`


In [14]:
# Element-wise

print(tensor, "*" ,tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [15]:
# matrix multiplication

torch.matmul(tensor, tensor)

tensor(14)

In [21]:
# time difference check
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]

print(value)

tensor(14)
CPU times: user 2.03 ms, sys: 2 µs, total: 2.04 ms
Wall time: 2.05 ms


In [20]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 1.04 ms, sys: 3 µs, total: 1.04 ms
Wall time: 925 µs


tensor(14)

In [28]:
#torch.matmul(torch.rand(3,2), torch.rand(3,2)) - will not work
#torch.matmul(torch.rand(3,2), torch.rand(2,3)) - will work

torch.matmul(torch.rand(3,2), torch.rand(2,3))

tensor([[0.4921, 1.1715, 1.1620],
        [0.0395, 0.0934, 0.0953],
        [0.4116, 0.9816, 0.9675]])

### One of the most common errors in deep learning: shape errors

In [34]:
# Shapes for matrix multiplication

tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

torch.mm(tensor_A, tensor_B) # torch.mm or torch.matmul


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

To fix out tensor shape issues, we can manipulate the shape of one of our tensor using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.

In [35]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [37]:
tensor_B.T.shape

torch.Size([2, 3])

In [48]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print("\n")
print(f"New shapes: tensor_A = {tensor_A.shape}, tesnor_B.T = {tensor_B.T.shape}")
print("\n")
#print(f"Multiplying tensor A and B = {tensor_A @ tensor_B.T}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("\n")
print("Output: \n")

output= torch.mm(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")


Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])


New shapes: tensor_A = torch.Size([3, 2]), tesnor_B.T = torch.Size([2, 3])


Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match


Output: 

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])
