<a href="https://colab.research.google.com/github/AJAYM888/Course_PyTorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals

In [35]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1+cu121


In [36]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


## Intro to tensors

### creating tensors

PyTorch tensor are created using 'torch.Tensor()' = add link

In [37]:
# scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [38]:
scalar.ndim

0

In [39]:
# get tensor back as python int

scalar.item()

7

In [40]:
# vector - has magnitude (how far) and direction (which way)
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [41]:
vector.ndim

1

In [42]:
vector.shape

torch.Size([2])

In [43]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [44]:
MATRIX.ndim

2

In [45]:
MATRIX[0]

tensor([7, 8])

In [46]:
MATRIX.shape

torch.Size([2, 2])

In [47]:
#TENSOR

TENSOR = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [48]:
TENSOR.shape

torch.Size([1, 3, 3])

In [49]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [50]:
#TENSOR

TENSOR = torch.tensor([[[[[1,2,3],[3,6,9],[2,4,5]]]]])
TENSOR

tensor([[[[[1, 2, 3],
           [3, 6, 9],
           [2, 4, 5]]]]])

In [51]:
#TENSOR

TENSOR = torch.tensor([[[[[1,2,3],[3,6,9],[2,4,5]]]]])
TENSOR

tensor([[[[[1, 2, 3],
           [3, 6, 9],
           [2, 4, 5]]]]])

In [52]:
TENSOR.ndim

5

In [53]:
TENSOR.shape

torch.Size([1, 1, 1, 3, 3])

In [54]:
#TENSOR

TENSOR = torch.tensor([[[[[1,2,3],[3,6,9],[2,4,5],[5,6,7]]]]])
TENSOR

tensor([[[[[1, 2, 3],
           [3, 6, 9],
           [2, 4, 5],
           [5, 6, 7]]]]])

In [55]:
TENSOR.ndim

5

In [56]:
TENSOR.shape

torch.Size([1, 1, 1, 4, 3])

In [57]:
#TENSOR

TENSOR = torch.tensor([[[[[1,2,3],[3,6,9],[2,4,5],[5,6,7], [7,8,9]]]]])
TENSOR

tensor([[[[[1, 2, 3],
           [3, 6, 9],
           [2, 4, 5],
           [5, 6, 7],
           [7, 8, 9]]]]])

In [58]:
TENSOR.ndim


5

In [59]:
TENSOR.shape

torch.Size([1, 1, 1, 5, 3])

In [60]:
#TENSOR

TENSOR = torch.tensor([[[[[1,2,3],[3,6,9],[2,4,5],[5,6,7], [7,8,9], [9,10,11]]]]])
TENSOR

tensor([[[[[ 1,  2,  3],
           [ 3,  6,  9],
           [ 2,  4,  5],
           [ 5,  6,  7],
           [ 7,  8,  9],
           [ 9, 10, 11]]]]])