<a href="https://colab.research.google.com/github/AJAYM888/Course_PyTorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1+cu121


In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


## Intro to tensors

### creating tensors

PyTorch tensor are created using 'torch.Tensor()' = add link

In [ ]:
# scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# get tensor back as python int

scalar.item()

7

In [ ]:
# vector - has magnitude (how far) and direction (which way)
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#TENSOR

TENSOR = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [ ]:
#TENSOR

TENSOR = torch.tensor([[[[[1,2,3],[3,6,9],[2,4,5]]]]])
TENSOR

tensor([[[[[1, 2, 3],
           [3, 6, 9],
           [2, 4, 5]]]]])

In [ ]:
#TENSOR

TENSOR = torch.tensor([[[[[1,2,3],[3,6,9],[2,4,5]]]]])
TENSOR

tensor([[[[[1, 2, 3],
           [3, 6, 9],
           [2, 4, 5]]]]])

In [ ]:
TENSOR.ndim

5

In [ ]:
TENSOR.shape

torch.Size([1, 1, 1, 3, 3])

In [ ]:
#TENSOR

TENSOR = torch.tensor([[[[[1,2,3],[3,6,9],[2,4,5],[5,6,7]]]]])
TENSOR

tensor([[[[[1, 2, 3],
           [3, 6, 9],
           [2, 4, 5],
           [5, 6, 7]]]]])

In [ ]:
TENSOR.ndim

5

In [ ]:
TENSOR.shape

torch.Size([1, 1, 1, 4, 3])

In [ ]:
#TENSOR

TENSOR = torch.tensor([[[[[1,2,3],[3,6,9],[2,4,5],[5,6,7], [7,8,9]]]]])
TENSOR

tensor([[[[[1, 2, 3],
           [3, 6, 9],
           [2, 4, 5],
           [5, 6, 7],
           [7, 8, 9]]]]])

In [ ]:
TENSOR.ndim


5

In [ ]:
TENSOR.shape

torch.Size([1, 1, 1, 5, 3])

In [ ]:
#TENSOR

TENSOR = torch.tensor([[[[[1,2,3],[3,6,9],[2,4,5],[5,6,7], [7,8,9], [9,10,11]]]]])
TENSOR

tensor([[[[[ 1,  2,  3],
           [ 3,  6,  9],
           [ 2,  4,  5],
           [ 5,  6,  7],
           [ 7,  8,  9],
           [ 9, 10, 11]]]]])

## Random Tensors

Why random tensors?

Rand tensors are important because the way many neural networks learn is that they start with tensor full of random numbers and then adjust those random numbers to better represent the data.


'start with rand numbers -> look at data -> update rand numbers -> look at data -> update random numbers'

In [ ]:
### create a random tensors of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor


tensor([[0.1000, 0.3180, 0.3293, 0.2707],
        [0.1834, 0.3980, 0.9114, 0.7280],
        [0.2271, 0.8037, 0.9872, 0.0295]])

In [ ]:
random_tensor.ndim

2

In [ ]:
# create a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(224, 224, 3)) #height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeros & Ones

In [ ]:
## create tensors with zeros & ones

zeros = torch.zeros(size=(3,4))
zeros
#zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(size=(4,4))
ones
#ones*random_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

## Tensor Range: Creating tensors with range & tensors-like

In [ ]:
# use torch.range
torch.arange(0,30)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
# use torch.range gets deprecated, use like below : arange()
two_twenty = torch.arange(start=2 , end=2000, step=200)
two_twenty

tensor([   2,  202,  402,  602,  802, 1002, 1202, 1402, 1602, 1802])

In [ ]:
# creating tensor like

ten_zeros = torch.zeros_like(input=two_twenty)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor DataTypes

**Note: ** Tensor datatypes is one of the three big issues in pytorch & DeepLearning
1. Tensors not right datatype
2. Tensor not in correct shape
3. Tensors not on the right device

In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None, device=None, requires_grad=False) # what datatype is the tensor (e.g. float32 or float16)
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)

#float_16_tensor = float_32_tensor.type(torch.half)

float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])