<a href="https://colab.research.google.com/github/AJAYM888/Course_PyTorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals

In [50]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1+cu121


In [51]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


## Intro to tensors

### creating tensors

PyTorch tensor are created using 'torch.Tensor()' = add link

In [52]:
# scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [53]:
scalar.ndim

0

In [54]:
# get tensor back as python int

scalar.item()

7

In [55]:
# vector - has magnitude (how far) and direction (which way)
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [56]:
vector.ndim

1

In [57]:
vector.shape

torch.Size([2])

In [58]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [59]:
MATRIX.ndim

2

In [60]:
MATRIX[0]

tensor([7, 8])

In [61]:
MATRIX.shape

torch.Size([2, 2])

In [62]:
#TENSOR

TENSOR = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [63]:
TENSOR.shape

torch.Size([1, 3, 3])

In [64]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [65]:
#TENSOR

TENSOR = torch.tensor([[[[[1,2,3],[3,6,9],[2,4,5]]]]])
TENSOR

tensor([[[[[1, 2, 3],
           [3, 6, 9],
           [2, 4, 5]]]]])

In [66]:
#TENSOR

TENSOR = torch.tensor([[[[[1,2,3],[3,6,9],[2,4,5]]]]])
TENSOR

tensor([[[[[1, 2, 3],
           [3, 6, 9],
           [2, 4, 5]]]]])

In [67]:
TENSOR.ndim

5

In [68]:
TENSOR.shape

torch.Size([1, 1, 1, 3, 3])

In [69]:
#TENSOR

TENSOR = torch.tensor([[[[[1,2,3],[3,6,9],[2,4,5],[5,6,7]]]]])
TENSOR

tensor([[[[[1, 2, 3],
           [3, 6, 9],
           [2, 4, 5],
           [5, 6, 7]]]]])

In [70]:
TENSOR.ndim

5

In [71]:
TENSOR.shape

torch.Size([1, 1, 1, 4, 3])

In [72]:
#TENSOR

TENSOR = torch.tensor([[[[[1,2,3],[3,6,9],[2,4,5],[5,6,7], [7,8,9]]]]])
TENSOR

tensor([[[[[1, 2, 3],
           [3, 6, 9],
           [2, 4, 5],
           [5, 6, 7],
           [7, 8, 9]]]]])

In [73]:
TENSOR.ndim


5

In [74]:
TENSOR.shape

torch.Size([1, 1, 1, 5, 3])

In [75]:
#TENSOR

TENSOR = torch.tensor([[[[[1,2,3],[3,6,9],[2,4,5],[5,6,7], [7,8,9], [9,10,11]]]]])
TENSOR

tensor([[[[[ 1,  2,  3],
           [ 3,  6,  9],
           [ 2,  4,  5],
           [ 5,  6,  7],
           [ 7,  8,  9],
           [ 9, 10, 11]]]]])

## Random Tensors

Why random tensors?

Rand tensors are important because the way many neural networks learn is that they start with tensor full of random numbers and then adjust those random numbers to better represent the data.


'start with rand numbers -> look at data -> update rand numbers -> look at data -> update random numbers'

In [76]:
### create a random tensors of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor


tensor([[0.4569, 0.3051, 0.4183, 0.9534],
        [0.5433, 0.7420, 0.5261, 0.3386],
        [0.9525, 0.6932, 0.9387, 0.2152]])

In [77]:
random_tensor.ndim

2

In [78]:
# create a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(224, 224, 3)) #height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeros & Ones

In [79]:
## create tensors with zeros & ones

zeros = torch.zeros(size=(3,4))
zeros
#zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [80]:
ones = torch.ones(size=(4,4))
ones
#ones*random_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [81]:
ones.dtype

torch.float32

## Tensor Range: Creating tensors with range & tensors-like

In [82]:
# use torch.range
torch.arange(0,30)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [83]:
# use torch.range gets deprecated, use like below : arange()
two_twenty = torch.arange(start=2 , end=2000, step=200)
two_twenty

tensor([   2,  202,  402,  602,  802, 1002, 1202, 1402, 1602, 1802])

In [84]:
# creating tensor like

ten_zeros = torch.zeros_like(input=two_twenty)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor DataTypes

**Note: ** Tensor datatypes is one of the three big issues in pytorch & DeepLearning
1. Tensors not right datatype
2. Tensor not in correct shape
3. Tensors not on the right device

In [85]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None, device=None, requires_grad=False) # what datatype is the tensor (e.g. float32 or float16)
float_32_tensor

tensor([3., 6., 9.])

In [86]:
# @title
float_16_tensor = float_32_tensor.type(torch.float16)

#float_16_tensor = float_32_tensor.type(torch.half)

float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [87]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [88]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [89]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

## Getting Information from tensors (tensor attributes)

1. Tensors not right datatype - to get datatype from a tensor, use tensor.dtype
2. Tensor not in correct shape - to get shape from a tensor, use tensor.shape
3. Tensors not on the right device - to get device from a tensor, use tensor.device


In [90]:
# create a tensor

some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.1985, 0.0205, 0.3319, 0.7226],
        [0.3067, 0.9594, 0.5744, 0.9240],
        [0.6367, 0.8699, 0.1239, 0.5158]])

In [91]:
# Find out details about tensor

print(some_tensor)
print(f"DataType of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.1985, 0.0205, 0.3319, 0.7226],
        [0.3067, 0.9594, 0.5744, 0.9240],
        [0.6367, 0.8699, 0.1239, 0.5158]])
DataType of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


## Manipulating Tensors (Tensor operations)

Tensor operations include:

* Addtion
* Substraction
* Multiplication (element-wise)
* Divison
* Matrix Multiplication

In [92]:
# create a tensor

tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [93]:
# Multiply tensor

tensor = torch.tensor([1,2,3])

tensor * 10

tensor([10, 20, 30])

In [94]:
# substration

tensor - 20

tensor([-19, -18, -17])

In [95]:
# Try out pytorch in-built functions

torch.mul(tensor, 20)
#torch.add(tensor, 20)
#torch.sub(tensor, 20)

tensor([20, 40, 60])

### Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

Docs: https://www.mathsisfun.com/algebra/matrix-multiplying.html
Calculator: http://matrixmultiplication.xyz/

There are two main rules that performing matrix multiplication needs to satisfy:

1. The **inner dimensions** must match:
* `(3,2) @ (3,2) ` won't work
* `(2,3) @ (3,2) ` will work
* `(3,2) @ (2,3) ` will work

2. The resulting matrix has the shape of the **outer dimensions**:

* `(3,2) @ (2,3)` -> `(2,2)`
* `(3,2) @ (2,3)` -> `(3,3)`


In [96]:
# Element-wise

print(tensor, "*" ,tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [97]:
# matrix multiplication

torch.matmul(tensor, tensor)

tensor(14)

In [98]:
# time difference check
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]

print(value)

tensor(14)
CPU times: user 1.19 ms, sys: 850 µs, total: 2.04 ms
Wall time: 2 ms


In [99]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 75 µs, sys: 7 µs, total: 82 µs
Wall time: 88.5 µs


tensor(14)

In [100]:
#torch.matmul(torch.rand(3,2), torch.rand(3,2)) - will not work
#torch.matmul(torch.rand(3,2), torch.rand(2,3)) - will work

torch.matmul(torch.rand(3,2), torch.rand(2,3))

tensor([[0.6297, 0.6130, 0.5833],
        [0.6120, 0.5988, 0.5698],
        [0.6266, 0.3212, 0.2980]])

### One of the most common errors in deep learning: shape errors

In [102]:
# Shapes for matrix multiplication

tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

torch.mm(tensor_A, tensor_B) # torch.mm or torch.matmul


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

To fix out tensor shape issues, we can manipulate the shape of one of our tensor using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.

In [103]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [104]:
tensor_B.T.shape

torch.Size([2, 3])

In [105]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print("\n")
print(f"New shapes: tensor_A = {tensor_A.shape}, tesnor_B.T = {tensor_B.T.shape}")
print("\n")
#print(f"Multiplying tensor A and B = {tensor_A @ tensor_B.T}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("\n")
print("Output: \n")

output= torch.mm(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")


Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])


New shapes: tensor_A = torch.Size([3, 2]), tesnor_B.T = torch.Size([2, 3])


Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match


Output: 

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


## Finding the min, max, mean, sum, etc (Tensor aggregation)

In [106]:
# create a tensor

x = torch.arange(10, 100, 10)

x

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [107]:
# Find min
torch.min(x), x.min()


(tensor(10), tensor(10))

In [108]:
# Find max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [109]:
# Find the mean - BEAUTIFUL EXAMPLE OF FINDING DATATYPE ERRORS - # Try torch.mean(x) - Needs float dtype

torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(50.), tensor(50.))

In [110]:
# Find the sum

torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding Positonal min and max values (index of min & max)

In [111]:
xy = torch.arange(5, 90, 5)

xy

tensor([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85])

In [112]:
# index minimum
torch.argmin(xy), xy.argmin()

(tensor(0), tensor(0))

In [113]:
# index maximum - useful during softmax activation function - will understand later
torch.argmax(xy), xy.argmax()

(tensor(16), tensor(16))

In [114]:
xy[0], xy[16]

(tensor(5), tensor(85))

## Reshaping, stacking, squeezing, & unsqeezing tensors - purpose of this is to manipulate the tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensor on top of each other (vstack), side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - return a view of the input with dimensions permuted (swapped) in a certain way

In [115]:
import torch
x = torch.arange(1. , 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [116]:
# reshape - Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [117]:
# reshape - Add an extra dimension
#x_reshaped = x.reshape(9, 1)
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [118]:
# Change the view

z = x.view(1,9)
z, z.shape


(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [119]:
# changing z changes x (because a view of a tensor shares the same memory as the original input)#
z[:,0] = 100
z, x

(tensor([[100.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.]]),
 tensor([100.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.]))

In [120]:
# stack tensors on top of each other

x_stacked = torch.stack([x,x,x], dim=0)
x_stacked

tensor([[100.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.],
        [100.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.],
        [100.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.]])

In [121]:
# stack tensors on top of each other

x_stacked = torch.stack([x,x,x], dim=1)
x_stacked

tensor([[100., 100., 100.],
        [  2.,   2.,   2.],
        [  3.,   3.,   3.],
        [  4.,   4.,   4.],
        [  5.,   5.,   5.],
        [  6.,   6.,   6.],
        [  7.,   7.,   7.],
        [  8.,   8.,   8.],
        [  9.,   9.,   9.]])

In [122]:
# Squeeze - removes all single dimensions from target tensor

x_reshaped, x_reshaped.shape

(tensor([[100.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.]]),
 torch.Size([1, 9]))

In [123]:
x_reshaped.squeeze()

tensor([100.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.])

In [124]:
x_reshaped.squeeze().size()

torch.Size([9])

In [125]:
print(f"original x_reshaped: {x_reshaped}")
print("\n")
print(f"original x_reshaped_size is: {x_reshaped.size()}")

print("\n")

x_squeezed = x_reshaped.squeeze()
# Removes extra dimensions from x_reshaped
print(f"squeezed x_reshaped: {x_squeezed}")
print("\n")

print(f"squeezed x_reshaped size: {x_squeezed.shape}")

original x_reshaped: tensor([[100.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.]])


original x_reshaped_size is: torch.Size([1, 9])


squeezed x_reshaped: tensor([100.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.])


squeezed x_reshaped size: torch.Size([9])


In [126]:
# unsqueeze - adds a single dimension to a target tensor at a specific dimension

print(f"previous squeezed x_reshaped size: {x_squeezed}")
print(f"previous squeezed x_reshaped size: {x_squeezed.shape}")
print("\n")

# adds extra dimensions to x_reshaped
x_unsqueezed = x_squeezed.unsqueeze(dim=0)

print(f"previous squeezed x_reshaped size: {x_unsqueezed}")
print(f"previous squeezed x_reshaped size: {x_unsqueezed.shape}")

previous squeezed x_reshaped size: tensor([100.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.])
previous squeezed x_reshaped size: torch.Size([9])


previous squeezed x_reshaped size: tensor([[100.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.]])
previous squeezed x_reshaped size: torch.Size([1, 9])


In [127]:
# Permuting tensors - rearranges the dimensions of a target tensor in a specified order - used generally in images
x_original = torch.rand(size=(224,224,3)) # [height, width, color_channels]

# permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"previous shape: {x_original.shape}")

print(f"new shape size: {x_permuted.shape}")
print("\n")
#print(f"new shape: {x_permuted}")


previous shape: torch.Size([224, 224, 3])
new shape size: torch.Size([3, 224, 224])




In [128]:
x_original[0,0,0] = 707007

x_original[0,0,0], x_permuted[0,0,0]

(tensor(707007.), tensor(707007.))

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [129]:
# create a tensor
import torch

x = torch.arange(1,16).reshape(1,5,3)
x, x.shape

(tensor([[[ 1,  2,  3],
          [ 4,  5,  6],
          [ 7,  8,  9],
          [10, 11, 12],
          [13, 14, 15]]]),
 torch.Size([1, 5, 3]))

In [130]:
# Let's index on our new tensor

x[0]

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15]])

In [131]:
# Let's index on middle bracket

x[0, 4]
#x[0][1]

tensor([13, 14, 15])

In [132]:
# Let's index on the most inner bracket (last dimension)

x[0,1,1]

tensor(5)

In [133]:
x[0,2,2]

tensor(9)

In [134]:
# you can also use ":" to select "all" of a target dimension
x[:, 1, 2]
x[:, :, 2]

tensor([[ 3,  6,  9, 12, 15]])

## PyTorch tensors & NumPy

NumPy is a popular scientific python numerical computing library.

& because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

* **Note:** Default numpy datatype is float64
* **warning:** when converting from numy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise.

In [143]:
# NumPy array to tensor

import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)

array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [144]:
# Change the value of array, what will this do to `tensor`?

array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [145]:
# Tensor to NumPy array

tensor = torch.ones(7)
numpy_tensor = tensor.numpy()

tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

**In short how a neural network learns:**

`start with full of random numbers -> tensor operations -> update random numberss to try & make them better representations of the data -> again -> again -> again......`

* To reduce the randomness in neural network and PyTorch comes the concept of **random seed**. Essentially what the random seed does is "flavour" the randomness

**Additonal resources:** https://pytorch.org/docs/stable/notes/randomness.html

**Random seed** = https://en.wikipedia.org/wiki/Random_seed

In [150]:
import torch

# create two random tensors

random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A==random_tensor_B)

tensor([[5.5783e-02, 8.2816e-01, 8.1829e-01, 9.6403e-01],
        [3.5642e-01, 8.0871e-01, 8.7037e-02, 7.5006e-04],
        [7.4949e-01, 9.2208e-01, 5.2485e-01, 2.0814e-02]])
tensor([[0.0951, 0.8742, 0.0774, 0.3934],
        [0.0212, 0.3143, 0.5748, 0.8211],
        [0.6544, 0.3376, 0.0182, 0.2253]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [158]:
# let's make some random but reproducible tensors

import torch

# set the random seed
RANDOM_SEED = 55
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED) # only duplicated or 2nd time in notebooks
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C==random_tensor_D)

tensor([[0.8357, 0.9378, 0.7439, 0.5674],
        [0.8682, 0.4765, 0.0858, 0.7740],
        [0.9677, 0.1874, 0.0993, 0.0611]])
tensor([[0.8357, 0.9378, 0.7439, 0.5674],
        [0.8682, 0.4765, 0.0858, 0.7740],
        [0.9677, 0.1874, 0.0993, 0.0611]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
